name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

env:
  HUSKY: 0

jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run linting
        run: biome lint

  typescript:
    name: Type checking
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, macos-13, windows-2019]
        node: [18, 20, 21, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
        env:
          NODE_VERSION: ${{ matrix.node }}

      - name: Run type checking
        run: pnpm run build

  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run formatting
        run: biome format && prettier --check **/*.{md,yaml}

  unit:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, macos-13, windows-2019]
        node: [18, 20, 21, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
        env:
          NODE_VERSION: ${{ matrix.node }}

      - name: Run tests
        run: pnpm run test
