name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

env:
  HUSKY: 0

jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run linting
        run: biome lint

  typescript:
    name: Type checking
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 20, 21, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v4
        env:
          NODE_VERSION: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci
      - name: Run type checking
        run: npm run build

  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run formatting
        run: biome format && prettier --check **/*.{md,yaml}

  unit:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20, 21, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v4
        env:
          NODE_VERSION: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run build

      - name: Run tests
        run: npm run test
